### ISSUE TITLE
compiling error: ‘PyString_xxx’ was not declared in this scope

### ISSUE THREAD

**Issue by StatML** [facebookarchive/caffe2#334]
Hi, I am building the framework on Ubuntu 16.04 with CUDA 8.0, and I get some compilation errors which are shown as follows:

caffe2/python/pybind_state.cc: In member function ‘virtual bool caffe2::python::PythonOpBase::RunOnDevice()’:
caffe2/python/pybind_state.cc:202:74: error: ‘PyString_AsString’ was not declared in this scope
             PyString_AsString(trace_vec[i]->tb_frame->f_code->co_filename);
                                                                          ^
caffe2/python/pybind_state.cc: In lambda function:
caffe2/python/pybind_state.cc:322:41: error: ‘PyString_Check’ was not declared in this scope
             if (PyString_Check(arg.ptr())) { // string
                                         ^
caffe2/python/pybind_state.cc: In lambda function:
caffe2/python/pybind_state.cc:824:37: error: ‘PyString_Check’ was not declared in this scope
         if (PyString_Check(arg.ptr())) { // string
                                     ^
caffe2/CMakeFiles/caffe2_pybind11_state.dir/build.make:62: recipe for target 'caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state.cc.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state.cc.o] Error 1
CMakeFiles/Makefile2:3346: recipe for target 'caffe2/CMakeFiles/caffe2_pybind11_state.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2_pybind11_state.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Yangqing** [comment]
Ah, we do not support Py3 yet - it is upcoming. Kindly check out #315 for updates.
