### ISSUE TITLE
Build error in Mac 10.12.4

### ISSUE THREAD

**Issue by malreddysid** [facebookarchive/caffe2#618]
I tried installing caffe2 from source and got the following error.

```[ 75%] Linking CXX shared library libCaffe2_CPU.dylib

Undefined symbols for architecture x86_64:
  "cv::_InputArray::_InputArray(cv::Mat const&)", referenced from:
      caffe2::ImageInputOp<caffe2::CPUContext>::GetImageAndLabelAndInfoFromDBValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cv::Mat*, caffe2::ImageInputOp<caffe2::CPUContext>::PerImageArg&, int) in image_input_op.cc.o
  "cv::_OutputArray::_OutputArray(cv::Mat&)", referenced from:
      caffe2::ImageInputOp<caffe2::CPUContext>::GetImageAndLabelAndInfoFromDBValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cv::Mat*, caffe2::ImageInputOp<caffe2::CPUContext>::PerImageArg&, int) in image_input_op.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Does anybody know how to fix this? I can get it to build by disabling opencv when doing cmake, but can't get it to work with opencv. I tried reinstalling opencv with homebrew but that didn't work.

**Comment by ghost** [comment]
I have the same issue. `clang -v` gives

```
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by pietern** [comment]
I'm going through and closing old issues. If this is still a problem, please feel free to open a new issue.

FWIW, we have been running continuous builds on macOS 10.13 (High Sierra).
