### ISSUE TITLE
Compile error related to gloo (class gloo::xxx::xxx has no member named xxx)

### ISSUE THREAD

**Issue by dbermond** [facebookarchive/caffe2#1044]
I'm getting this compile error:
```
[ 13%] Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/core/blob_serialization.cc.o
In file included from /storage/linux/abs/caffe2-git/src/caffe2-git/caffe2/contrib/gloo/common_world_ops.cc:1:0:
/storage/linux/abs/caffe2-git/src/caffe2-git/caffe2/contrib/gloo/common_world_ops.h: In member function ‘bool caffe2::gloo::CreateCommonWorld<Context>::RunOnDevice()’:
/storage/linux/abs/caffe2-git/src/caffe2-git/caffe2/contrib/gloo/common_world_ops.h:72:26: error: ‘class gloo::transport::Device’ has no member named ‘getTimeout’
                 device_->getTimeout()) {
                          ^
/storage/linux/abs/caffe2-git/src/caffe2-git/caffe2/contrib/gloo/common_world_ops.h: In instantiation of ‘bool caffe2::gloo::CreateCommonWorld<Context>::RunOnDevice() [with Context = caffe2::CPUContext]’:
/storage/linux/abs/caffe2-git/src/caffe2-git/caffe2/contrib/gloo/common_world_ops.cc:33:1:   required from here
/storage/linux/abs/caffe2-git/src/caffe2-git/caffe2/contrib/gloo/common_world_ops.h:71:13: error: ‘class gloo::Context’ has no member named ‘getDevice’
             backingCommonWorld->getDevice()->getTimeout() <
             ^
make[2]: *** [caffe2/CMakeFiles/Caffe2_CPU.dir/build.make:159: caffe2/CMakeFiles/Caffe2_CPU.dir/contrib/gloo/common_world_ops.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:561: caffe2/CMakeFiles/Caffe2_CPU.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

A git bissect shows that it's being caused by commit e4be658fd4591cd38fbefb2abd3acaa59f4823c3, but maybe this is wrong because other different errors appeared during the bisect compile tests. Maybe this is related to gloo being updated to git master by commit 3a31edb1bfcae07dff2194f044382a197584fe95?

This happens on both gpu-enabled and cpu-only builds.

**System information:**
**OS:** Arch Linux x86_64
**caffe2:** git master (currently at 0.8.0.r148.g9f46ce87)
**compiler:** gcc 5.4.0

**Comment by StatML** [comment]
I met the same problem.

**Comment by StatML** [comment]
Hi @Yangqing Can you help fixing this? Thx a lot!

**Comment by dbermond** [comment]
Recent commits have fixed this error for me. The most recent git master source code at the time of this writing (0.8.1.r19.gf0ea8046) is now building fine.

@StatML 
I will be closing this issue because I have opened it and it's now solved for me. If you still have such an issue like this, please open a new topic.

You did not mentioned your operating system, but if you are on Arch Linux I have updated the Caffe2 packages on the AUR and all of them are building fine now.

**Comment by StatML** [comment]
@dbermond Thanks! This issue is still not solved for me. My platform is Ubuntu 16.04.4, G++5.4.0, Python3.5.2. I will open a new topic.
