### ISSUE TITLE
Error when build on Jetson TX2 with newest Jetpack 3.1

### ISSUE THREAD

**Issue by superying** [facebookarchive/caffe2#965]
When I run the build_tegra_x1.sh to build on Jetson TX2 after update Jetpack to 3.1, I get a weird error:

[ 76%] Built target Caffe2_GPU
Scanning dependencies of target reshape_op_gpu_test
Scanning dependencies of target context_test
Scanning dependencies of target utility_ops_gpu_test
Scanning dependencies of target utility_ops_test
[ 77%] Building CXX object caffe2/CMakeFiles/context_test.dir/core/context_test.cc.o
[ 77%] Building CXX object caffe2/CMakeFiles/reshape_op_gpu_test.dir/operators/reshape_op_gpu_test.cc.o
[ 78%] Building CXX object caffe2/CMakeFiles/utility_ops_gpu_test.dir/operators/utility_ops_gpu_test.cc.o
[ 78%] Building CXX object caffe2/CMakeFiles/utility_ops_test.dir/operators/utility_ops_test.cc.o
[ 78%] Linking CXX executable binaries/context_test
libCaffe2_CPU.so: undefined reference to `void caffe2::TypedAxpy<caffe2::__f16, float>(int, float, caffe2::__f16 const*, float*)'
libCaffe2_CPU.so: undefined reference to `void caffe2::TypedAxpy<float, float>(int, float, float const*, float*)'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/context_test.dir/build.make:135: recipe for target 'caffe2/binaries/context_test' failed
make[2]: *** [caffe2/binaries/context_test] Error 1
CMakeFiles/Makefile2:1523: recipe for target 'caffe2/CMakeFiles/context_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/context_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 78%] Linking CXX executable binaries/reshape_op_gpu_test
libCaffe2_CPU.so: undefined reference to `void caffe2::TypedAxpy<caffe2::__f16, float>(int, float, caffe2::__f16 const*, float*)'
libCaffe2_CPU.so: undefined reference to `void caffe2::TypedAxpy<float, float>(int, float, float const*, float*)'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/reshape_op_gpu_test.dir/build.make:135: recipe for target 'caffe2/binaries/reshape_op_gpu_test' failed
make[2]: *** [caffe2/binaries/reshape_op_gpu_test] Error 1
CMakeFiles/Makefile2:1439: recipe for target 'caffe2/CMakeFiles/reshape_op_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/reshape_op_gpu_test.dir/all] Error 2
[ 78%] Linking CXX executable binaries/utility_ops_gpu_test
[ 78%] Linking CXX executable binaries/utility_ops_test
libCaffe2_CPU.so: undefined reference to `void caffe2::TypedAxpy<caffe2::__f16, float>(int, float, caffe2::__f16 const*, float*)'
libCaffe2_CPU.so: undefined reference to `void caffe2::TypedAxpy<float, float>(int, float, float const*, float*)'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/utility_ops_test.dir/build.make:135: recipe for target 'caffe2/binaries/utility_ops_test' failed
make[2]: *** [caffe2/binaries/utility_ops_test] Error 1
CMakeFiles/Makefile2:1565: recipe for target 'caffe2/CMakeFiles/utility_ops_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/utility_ops_test.dir/all] Error 2
libCaffe2_CPU.so: undefined reference to `void caffe2::TypedAxpy<caffe2::__f16, float>(int, float, caffe2::__f16 const*, float*)'
libCaffe2_CPU.so: undefined reference to `void caffe2::TypedAxpy<float, float>(int, float, float const*, float*)'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/utility_ops_gpu_test.dir/build.make:135: recipe for target 'caffe2/binaries/utility_ops_gpu_test' failed
make[2]: *** [caffe2/binaries/utility_ops_gpu_test] Error 1
CMakeFiles/Makefile2:1481: recipe for target 'caffe2/CMakeFiles/utility_ops_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/utility_ops_gpu_test.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

It seems that the caffe2::TypedAxpy functions are missing. Any ideas?

**Comment by Yangqing** [comment]
My fault - this is due to our recent effort of adding multi-dispatching capability in caffe2, which broke the cmake build system. This should fix it once it lands: #967
