### ISSUE TITLE
Build fail on Ubuntu 16.04 Cuda 8 and cuDNN 5 or 6

### ISSUE THREAD

**Issue by ucsky** [facebookarchive/caffe2#1584]
Trying to build  on Ubuntu 16.04 with Cuda 8 and cuDNN 5 or 6 I get the following error:

```
[ 55%] Built target caffe2
[ 55%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/utils/caffe2_gpu_generated_math_gpu.cu.o
/home/bob/setup/tec/caffe2/caffe2/caffe2/core/common_cudnn.h(142): error: identifier "CUDNN_DATA_INT32" is undefined

1 error detected in the compilation of "/tmp/tmpxft_00001d3a_00000000-19_math_gpu.compute_61.cpp1.ii".
CMake Error at caffe2_gpu_generated_math_gpu.cu.o.cmake:262 (message):
  Error generating file
    /home/bob/setup/tec/caffe2/caffe2/build/caffe2/CMakeFiles/caffe2_gpu.dir/utils/./caffe2_gpu_generated_math_gpu.cu.o

caffe2/CMakeFiles/caffe2_gpu.dir/build.make:672: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/utils/caffe2_gpu_generated_math_gpu.cu.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/utils/caffe2_gpu_generated_math_gpu.cu.o] Error 1
CMakeFiles/Makefile2:2257: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```
Please do you known how I can fix this?

**Comment by pietern** [comment]
We run builds for Ubuntu 16.04 with CUDA 8 and cuDNN 6 and those are fine.

Are you trying to build with cuDNN 5?

**Comment by ucsky** [comment]
```
cat /usr/local/cuda/version.txt
```
give
```
CUDA Version 8.0.61
```

**Comment by pietern** [comment]
Which cuDNN version are you trying to use? Can you post the CMake summary output?

**Comment by pietern** [comment]
This is likely caused by trying to compile with cuDNN 5.1. I suggest upgrading to version 7.

I created an issue to gauge interest in reviving support for cuDNN 5.1 in #1607.

**Comment by Yangqing** [comment]
Fixed by https://github.com/caffe2/caffe2/commit/55f6fea3a93a4e9e1d1256e1ec51afa1d4ce6f70 although we might not support cudnn 5.1 in the long term, so you might want to consider updating cudnn.
