### ISSUE TITLE
Compile error...

### ISSUE THREAD

**Issue by Raidin** [facebookarchive/caffe2#772]
Hi, I'm building the framework on Ubuntu 14.04 using CUDA 7.5, A compilation error occurs.

[ 18%] Building NVCC (Device) object third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/gloo_cuda_generated_cuda_private.cu.o
/home/jihunjung/caffe2/third_party/gloo/gloo/cuda_private.cu(40): error: identifier "__int2half_rn" is undefined

1 error detected in the compilation of "/tmp/tmpxft_00003a82_00000000-7_cuda_private.cpp1.ii".
CMake Error at gloo_cuda_generated_cuda_private.cu.o.Release.cmake:278 (message):
  Error generating file
  /home/jihunjung/caffe2/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir//./gloo_cuda_generated_cuda_private.cu.o

How to solve this error??

**Comment by akshay-raj-dhamija** [comment]
Not sure, but a temporary fix might be to build without gloo using `-DUSE_GLOO=OFF` in your Makefile

**Comment by pietern** [comment]
cc @wesolwsk

**Comment by wesolwsk** [comment]
Looks like that particular function is only supported in CUDA 8.0. We can use __float2half_rn instead to make this more portable.

**Comment by attitudechunfeng** [comment]
@wesolwsk Could you show some more details about how to use __float2half_rn to instead __int2half_rn?
