### ISSUE TITLE
build fails with “recipe for target 'caffe2/CMakeFiles/boolean_unmask_ops_test.dir/all' failed” on Ubuntu 17.04

### ISSUE THREAD

**Issue by ihendley** [facebookarchive/caffe2#1592]
I am trying to build on Ubuntu 17.04 and with CUDA 9 and cuDNN 7. I have installed all the dependencies per the installation instructions [here](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile), but I get the following error:

`[ 76%] Linking CXX executable ../bin/boolean_unmask_ops_test /usr/bin/cmake: /home/imran/.pyenv/versions/anaconda3-4.4.0/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake) CMakeFiles/boolean_unmask_ops_test.dir/operators/boolean_unmask_ops_test.cc.o: In function caffe2::BooleanUnmaskTest_Test_Test::TestBody()':
  boolean_unmask_ops_test.cc:(.text+0x1557): undefined reference togoogle::protobuf::internal::fixed_address_empty_string[abi:cxx11]' /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4.9: undefined reference to TIFFReadRGBAStrip@LIBTIFF_4.0'
  ../lib/libcaffe2.so: undefined reference togoogle::protobuf::internal::AssignDescriptors(std::__cxx11::basic_string, std::allocator > const&, google::protobuf::internal::MigrationSchema const*, google::protobuf::Message const* const*, unsigned int const*, google::protobuf::MessageFactory*, google::protobuf::Metadata*, google::protobuf::EnumDescriptor const**, google::protobuf::ServiceDescriptor const**)' ../lib/libcaffe2.so: undefined reference to google::protobuf::MessageLite::SerializeAsString[abi:cxx11]() const'
  ../lib/libcaffe2.so: undefined reference togoogle::protobuf::MessageLite::SerializeToString(std::__cxx11::basic_string, std::allocator >) const' ../lib/libcaffe2.so: undefined reference to google::protobuf::internal::WireFormatLite::WriteBytes(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
  /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4.9: undefined reference toTIFFIsTiled@LIBTIFF_4.0' ../lib/libcaffe2.so: undefined reference to typeinfo for std::thread::_State'
  ../lib/libcaffe2.so: undefined reference togoogle::protobuf::Message::ShortDebugStringabi:cxx11 const' /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4.9: undefined reference to TIFFWriteScanline@LIBTIFF_4.0'
  ../lib/libcaffe2.so: undefined reference togoogle::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::__cxx11::basic_string, std::allocator > const&, google::protobuf::io::CodedOutputStream)' ../lib/libcaffe2.so: undefined reference to google::protobuf::Message::GetTypeName[abi:cxx11]() const'
  /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4.9: undefined reference toTIFFGetField@LIBTIFF_4.0' ../lib/libcaffe2.so: undefined reference to std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())'
  /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4.9: undefined reference toTIFFScanlineSize@LIBTIFF_4.0' ../lib/libcaffe2.so: undefined reference to google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
  ../lib/libcaffe2.so: undefined reference togoogle::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string, std::allocator > const&, unsigned char*)' /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4.9: undefined reference to TIFFReadEncodedTile@LIBTIFF_4.0'
  /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4.9: undefined reference toTIFFReadRGBATile@LIBTIFF_4.0' /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4.9: undefined reference to TIFFClose@LIBTIFF_4.0'
  /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4.9: undefined reference toTIFFRGBAImageOK@LIBTIFF_4.0' ../lib/libcaffe2.so: undefined reference to google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
  ../lib/libcaffe2.so: undefined reference togoogle::protobuf::TextFormat::ParseFromString(std::__cxx11::basic_string, std::allocator > const&, google::protobuf::Message*)' ../lib/libcaffe2.so: undefined reference to google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, google::protobuf::internal::ArenaStringPtr)'
  /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4.9: undefined reference toTIFFOpen@LIBTIFF_4.0' /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4.9: undefined reference to TIFFReadEncodedStrip@LIBTIFF_4.0'
  ../lib/libcaffe2.so: undefined reference togoogle::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void ()(std::__cxx11::basic_string, std::allocator > const&))' ../lib/libcaffe2.so: undefined reference to google::protobuf::internal::ParseNamedEnum(google::protobuf::EnumDescriptor const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int*)'
  /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4.9: undefined reference toTIFFSetField@LIBTIFF_4.0' ../lib/libcaffe2.so: undefined reference to google::protobuf::MessageLite::ParseFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
  ../lib/libcaffe2.so: undefined reference togoogle::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream, std::__cxx11::basic_string, std::allocator >)' /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4.9: undefined reference to TIFFSetWarningHandler@LIBTIFF_4.0'
  /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4.9: undefined reference toTIFFSetErrorHandler@LIBTIFF_4.0' ../lib/libcaffe2.so: undefined reference to std::thread::_State::~_State()'
  ../lib/libcaffe2.so: undefined reference togoogle::protobuf::internal::WireFormatLite::WriteString(int, std::__cxx11::basic_string, std::allocator > const&, google::protobuf::io::CodedOutputStream)' collect2: error: ld returned 1 exit status caffe2/CMakeFiles/boolean_unmask_ops_test.dir/build.make:114: recipe for target 'bin/boolean_unmask_ops_test' failed make[3]: * [bin/boolean_unmask_ops_test] Error 1 make[3]: Leaving directory '/home/imran/caffe2/build' CMakeFiles/Makefile2:924: recipe for target 'caffe2/CMakeFiles/boolean_unmask_ops_test.dir/all' failed make[2]: [caffe2/CMakeFiles/boolean_unmask_ops_test.dir/all] Error 2 make[2]: Leaving directory '/home/imran/caffe2/build' Makefile:138: recipe for target 'all' failed make[1]: [all] Error 2 make[1]: Leaving directory '/home/imran/caffe2/build' Makefile:4: recipe for target 'all' failed make: * [all] Error 2`

**Comment by pietern** [comment]
This issue is probably related to mixing Anaconda packages with system packages.

It is possible that you have OpenCV installed as Anaconda package, but ALSO as system package. Then at link/load time when it tries to link/load OpenCV, it also tried to load libtiff.so and finds the system package instead of the Anaconda package.

Can you post the CMake summary output?

**Comment by pjh5** [comment]
This should be tracked in #1881 so I will close this issue.
