### ISSUE TITLE
make the issues accured ../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'

### ISSUE THREAD

**Issue by zhang412yi** [facebookarchive/caffe2#1870]
Hi,
I have been trying to get Caffe 2 to work on Ubuntu16.04  with GPU/CUDA  and cmake -DCUDNN_INCLUDE_DIR=/usr/local/cuda/include/ -DCUDNN_LIBRARY=/usr/local/cuda/lib64/libcudnn.so -DCUDA_USE_STATIC_CUDA_RUNTIME=OFF ..
![_20180202141309](https://user-images.githubusercontent.com/27990874/35719200-3d87963a-0823-11e8-81dc-545b806288ec.png)
but when I make the issues accured
[ 82%] Linking CXX executable ../bin/init_test
[ 82%] Linking CXX executable ../bin/common_test
[ 82%] Linking CXX executable ../bin/fatal_signal_asan_no_sig_test
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/cpuid_test.dir/build.make:131: recipe for target 'bin/cpuid_test' failed
make[2]: *** [bin/cpuid_test] Error 1
CMakeFiles/Makefile2:1469: recipe for target 'caffe2/CMakeFiles/cpuid_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/cpuid_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 82%] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir/python/pybind_state_dlpack.cc.o
[ 82%] Linking CXX executable ../bin/logging_test
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/timer_test.dir/build.make:131: recipe for target 'bin/timer_test' failed
make[2]: *** [bin/timer_test] Error 1
caffe2/CMakeFiles/fixed_divisor_test.dir/build.make:131: recipe for target 'bin/fixed_divisor_test' failed
make[2]: *** [bin/fixed_divisor_test] Error 1
CMakeFiles/Makefile2:2372: recipe for target 'caffe2/CMakeFiles/timer_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/timer_test.dir/all] Error 2
CMakeFiles/Makefile2:1813: recipe for target 'caffe2/CMakeFiles/fixed_divisor_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/fixed_divisor_test.dir/all] Error 2
[ 82%] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state_dlpack.cc.o
[ 82%] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir/python/pybind_state_mkl.cc.o
[ 82%] Linking CXX executable ../bin/smart_tensor_printer_test
[ 82%] Linking CXX executable ../bin/typeid_test
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/init_test.dir/build.make:131: recipe for target 'bin/init_test' failed
make[2]: *** [bin/init_test] Error 1
caffe2/CMakeFiles/registry_test.dir/build.make:131: recipe for target 'bin/registry_test' failed
make[2]: *** [bin/registry_test] Error 1
CMakeFiles/Makefile2:2028: recipe for target 'caffe2/CMakeFiles/init_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/init_test.dir/all] Error 2
CMakeFiles/Makefile2:1641: recipe for target 'caffe2/CMakeFiles/registry_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/registry_test.dir/all] Error 2
[ 82%] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir/python/pybind_state_gpu.cc.o
[ 82%] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state_mkl.cc.o
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/common_test.dir/build.make:131: recipe for target 'bin/common_test' failed
make[2]: *** [bin/common_test] Error 1
CMakeFiles/Makefile2:1598: recipe for target 'caffe2/CMakeFiles/common_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/common_test.dir/all] Error 2
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
[ 83%] Linking CXX executable ../bin/event_gpu_test
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/fatal_signal_asan_no_sig_test.dir/build.make:131: recipe for target 'bin/fatal_signal_asan_no_sig_test' failed
make[2]: *** [bin/fatal_signal_asan_no_sig_test] Error 1
CMakeFiles/Makefile2:1512: recipe for target 'caffe2/CMakeFiles/fatal_signal_asan_no_sig_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/fatal_signal_asan_no_sig_test.dir/all] Error 2
[ 83%] Linking CXX executable ../bin/context_gpu_test
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/logging_test.dir/build.make:131: recipe for target 'bin/logging_test' failed
make[2]: *** [bin/logging_test] Error 1
caffe2/CMakeFiles/smart_tensor_printer_test.dir/build.make:131: recipe for target 'bin/smart_tensor_printer_test' failed
make[2]: *** [bin/smart_tensor_printer_test] Error 1
CMakeFiles/Makefile2:2200: recipe for target 'caffe2/CMakeFiles/logging_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/logging_test.dir/all] Error 2
CMakeFiles/Makefile2:2458: recipe for target 'caffe2/CMakeFiles/smart_tensor_printer_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/smart_tensor_printer_test.dir/all] Error 2
[ 83%] Linking CXX executable ../bin/stats_test
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/typeid_test.dir/build.make:131: recipe for target 'bin/typeid_test' failed
make[2]: *** [bin/typeid_test] Error 1
CMakeFiles/Makefile2:1727: recipe for target 'caffe2/CMakeFiles/typeid_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/typeid_test.dir/all] Error 2
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/event_gpu_test.dir/build.make:131: recipe for target 'bin/event_gpu_test' failed
make[2]: *** [bin/event_gpu_test] Error 1
CMakeFiles/Makefile2:1899: recipe for target 'caffe2/CMakeFiles/event_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/event_gpu_test.dir/all] Error 2
[ 83%] Linking CXX executable ../bin/operator_gpu_test
[ 83%] Linking CXX executable ../bin/operator_schema_test
[ 83%] Linking CXX executable ../bin/predictor_test
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/context_gpu_test.dir/build.make:131: recipe for target 'bin/context_gpu_test' failed
make[2]: *** [bin/context_gpu_test] Error 1
CMakeFiles/Makefile2:1383: recipe for target 'caffe2/CMakeFiles/context_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/context_gpu_test.dir/all] Error 2
[ 83%] Linking CXX executable ../bin/module_test
[ 84%] Linking CXX executable ../bin/workspace_test
[ 84%] Linking CXX executable ../bin/graph_test
[ 84%] Linking CXX executable ../bin/reshape_op_gpu_test
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
[ 84%] Linking CXX executable ../bin/mpi_gpu_test
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/stats_test.dir/build.make:131: recipe for target 'bin/stats_test' failed
make[2]: *** [bin/stats_test] Error 1
CMakeFiles/Makefile2:1942: recipe for target 'caffe2/CMakeFiles/stats_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/stats_test.dir/all] Error 2
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/operator_gpu_test.dir/build.make:131: recipe for target 'bin/operator_gpu_test' failed
make[2]: *** [bin/operator_gpu_test] Error 1
CMakeFiles/Makefile2:1340: recipe for target 'caffe2/CMakeFiles/operator_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/operator_gpu_test.dir/all] Error 2
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
[ 85%] Linking CXX executable ../bin/net_gpu_test
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/operator_schema_test.dir/build.make:131: recipe for target 'bin/operator_schema_test' failed
make[2]: *** [bin/operator_schema_test] Error 1
CMakeFiles/Makefile2:2114: recipe for target 'caffe2/CMakeFiles/operator_schema_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/operator_schema_test.dir/all] Error 2
[ 85%] Linking CXX executable ../bin/transform_test
[ 85%] Linking CXX executable ../bin/parallel_net_test
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/workspace_test.dir/build.make:131: recipe for target 'bin/workspace_test' failed
make[2]: *** [bin/workspace_test] Error 1
caffe2/CMakeFiles/module_test.dir/build.make:131: recipe for target 'bin/module_test' failed
make[2]: *** [bin/module_test] Error 1
caffe2/CMakeFiles/predictor_test.dir/build.make:131: recipe for target 'bin/predictor_test' failed
make[2]: *** [bin/predictor_test] Error 1
CMakeFiles/Makefile2:1426: recipe for target 'caffe2/CMakeFiles/workspace_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/workspace_test.dir/all] Error 2
CMakeFiles/Makefile2:1684: recipe for target 'caffe2/CMakeFiles/module_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/module_test.dir/all] Error 2
CMakeFiles/Makefile2:2329: recipe for target 'caffe2/CMakeFiles/predictor_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/predictor_test.dir/all] Error 2
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/mpi_gpu_test.dir/build.make:131: recipe for target 'bin/mpi_gpu_test' failed
make[2]: *** [bin/mpi_gpu_test] Error 1
CMakeFiles/Makefile2:2243: recipe for target 'caffe2/CMakeFiles/mpi_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/mpi_gpu_test.dir/all] Error 2
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/graph_test.dir/build.make:131: recipe for target 'bin/graph_test' failed
make[2]: *** [bin/graph_test] Error 1
CMakeFiles/Makefile2:1555: recipe for target 'caffe2/CMakeFiles/graph_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/graph_test.dir/all] Error 2
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/reshape_op_gpu_test.dir/build.make:131: recipe for target 'bin/reshape_op_gpu_test' failed
make[2]: *** [bin/reshape_op_gpu_test] Error 1
CMakeFiles/Makefile2:1211: recipe for target 'caffe2/CMakeFiles/reshape_op_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/reshape_op_gpu_test.dir/all] Error 2
[ 85%] Linking CXX executable ../bin/string_ops_test
[ 85%] Linking CXX executable ../bin/operator_fallback_gpu_test
[ 85%] Linking CXX executable ../bin/elementwise_op_gpu_test
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/transform_test.dir/build.make:131: recipe for target 'bin/transform_test' failed
make[2]: *** [bin/transform_test] Error 1
CMakeFiles/Makefile2:2071: recipe for target 'caffe2/CMakeFiles/transform_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/transform_test.dir/all] Error 2
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/net_gpu_test.dir/build.make:131: recipe for target 'bin/net_gpu_test' failed
make[2]: *** [bin/net_gpu_test] Error 1
CMakeFiles/Makefile2:2157: recipe for target 'caffe2/CMakeFiles/net_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/net_gpu_test.dir/all] Error 2
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/parallel_net_test.dir/build.make:131: recipe for target 'bin/parallel_net_test' failed
make[2]: *** [bin/parallel_net_test] Error 1
CMakeFiles/Makefile2:1770: recipe for target 'caffe2/CMakeFiles/parallel_net_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/parallel_net_test.dir/all] Error 2
[ 85%] Linking CXX executable ../bin/math_gpu_test
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/string_ops_test.dir/build.make:131: recipe for target 'bin/string_ops_test' failed
make[2]: *** [bin/string_ops_test] Error 1
CMakeFiles/Makefile2:2286: recipe for target 'caffe2/CMakeFiles/string_ops_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/string_ops_test.dir/all] Error 2
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/elementwise_op_gpu_test.dir/build.make:131: recipe for target 'bin/elementwise_op_gpu_test' failed
make[2]: *** [bin/elementwise_op_gpu_test] Error 1
caffe2/CMakeFiles/operator_fallback_gpu_test.dir/build.make:131: recipe for target 'bin/operator_fallback_gpu_test' failed
make[2]: *** [bin/operator_fallback_gpu_test] Error 1
CMakeFiles/Makefile2:1254: recipe for target 'caffe2/CMakeFiles/elementwise_op_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/elementwise_op_gpu_test.dir/all] Error 2
CMakeFiles/Makefile2:1297: recipe for target 'caffe2/CMakeFiles/operator_fallback_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/operator_fallback_gpu_test.dir/all] Error 2
[ 85%] Linking CXX executable ../bin/operator_test
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/math_gpu_test.dir/build.make:131: recipe for target 'bin/math_gpu_test' failed
make[2]: *** [bin/math_gpu_test] Error 1
CMakeFiles/Makefile2:1856: recipe for target 'caffe2/CMakeFiles/math_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/math_gpu_test.dir/all] Error 2
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/operator_test.dir/build.make:131: recipe for target 'bin/operator_test' failed
make[2]: *** [bin/operator_test] Error 1
CMakeFiles/Makefile2:2415: recipe for target 'caffe2/CMakeFiles/operator_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/operator_test.dir/all] Error 2
[ 85%] Linking CXX executable ../bin/blob_test
CMakeFiles/blob_test.dir/core/blob_test.cc.o: In function `caffe2::(anonymous namespace)::ContentChunks_Serialization_Test::TestBody()':
blob_test.cc:(.text+0x3b1f6): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
../lib/libcaffe2.so: undefined reference to `cpuinfo_deinitialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l4_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l2_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l1d_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_initialize'
../lib/libcaffe2.so: undefined reference to `cpuinfo_get_l3_cache'
../lib/libcaffe2.so: undefined reference to `cpuinfo_isa'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/blob_test.dir/build.make:131: recipe for target 'bin/blob_test' failed
make[2]: *** [bin/blob_test] Error 1
CMakeFiles/Makefile2:1985: recipe for target 'caffe2/CMakeFiles/blob_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/blob_test.dir/all] Error 2
[ 85%] Linking CXX shared module python/caffe2_pybind11_state_gpu.so
[ 85%] Linking CXX shared module python/caffe2_pybind11_state.so
[ 85%] Built target caffe2_pybind11_state
[ 85%] Built target caffe2_pybind11_state_gpu
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by CarryJzzZ** [comment]
I meet the same error, do you know how to solve it?

**Comment by CarryJzzZ** [comment]
I found that the NNPACK does not compile successful, it may cause the problem

**Comment by ZzzjzzZ** [comment]
I found it was a bug, and it has been fixed by Ma
@Maratyszcza , at #1869,  I re-download the caffe2,  and compile it, there are no errors.
