### ISSUE TITLE
Build error: attributes are not allowed on a function-definition

### ISSUE THREAD

**Issue by dbermond** [facebookarchive/caffe2#2374]
I'm getting the following error when trying to compile caffe2 git master:

```
[ 63%] Building CXX object caffe2/CMakeFiles/caffe2.dir/operators/index_hash_ops.cc.o
In file included from /storage/linux/abs/caffe2-cpu-git/src/caffe2-cpu-git/caffe2/operators/index_hash_ops.h:20:0,
                 from /storage/linux/abs/caffe2-cpu-git/src/caffe2-cpu-git/caffe2/operators/index_hash_ops.cc:17:
/storage/linux/abs/caffe2-cpu-git/src/caffe2-cpu-git/caffe2/core/asan.h:47:33: error: attributes are not allowed on a function-definition
 #define CAFFE2_NO_SANITIZE(...) __attribute__((no_sanitize(__VA_ARGS__)))
                                 ^
/storage/linux/abs/caffe2-cpu-git/src/caffe2-cpu-git/caffe2/operators/index_hash_ops.h:66:16: note: in expansion of macro ‘CAFFE2_NO_SANITIZE’
   T hash(T id) CAFFE2_NO_SANITIZE("signed-integer-overflow") {
                ^~~~~~~~~~~~~~~~~~
cc1plus: warning: unrecognized command line option ‘-Wno-invalid-partial-specialization’
make[2]: *** [caffe2/CMakeFiles/caffe2.dir/build.make:3519: caffe2/CMakeFiles/caffe2.dir/operators/index_hash_ops.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:870: caffe2/CMakeFiles/caffe2.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

I think this is probably caused by commit https://github.com/caffe2/caffe2/commit/f46f3004e38b211a76187b03c4bc9c1889369497.

Build/cmake configuration: https://bpaste.net/show/8d6a974727d7

### System information

* Operating system: Arch Linux x86_64
* Caffe2: git master
* Compiler version: gcc 7.3.1
* CMake version: 3.10.3
* CMake arguments: provided above
* Relevant libraries/versions (e.g. CUDA): cuda disabled in cmake

### CMake summary output

```
-- ******** Summary ********
-- General:
--   CMake version         : 3.10.3
--   CMake command         : /usr/bin/cmake
--   Git version           : v0.8.1-1400-ga63ed730f
--   System                : Linux
--   C++ compiler          : /usr/lib/ccache/bin/c++
--   C++ compiler version  : 7.3.1
--   Protobuf compiler     : /usr/bin/protoc
--   Protobuf include path : /usr/include
--   Protobuf libraries    : /usr/lib/libprotobuf.so
--   BLAS                  : Eigen
--   CXX flags             : -march=native -O2 -pipe -fstack-protector-strong -fno-plt -fsanitize=address -fPIE -pie -fopenmp -DONNX_NAMESPACE=onnx_c2 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_BINARY          : ON
--   BUILD_CUSTOM_PROTOBUF : OFF
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 3.6.4
--     Python includes     : /usr/include/python3.6m
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : OFF
--   USE_ATEN              : ON
--   USE_ASAN              : ON
--   USE_CUDA              : OFF
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : ON
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.20
--     Snappy version      : ..
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.21
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : OFF
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : OFF
--   USE_OPENMP            : ON
--   USE_PROF              : OFF
--   USE_REDIS             : ON
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : ON
-- Configuring done
-- Generating done
-- Build files have been written to: /storage/linux/abs/caffe2-cpu-git/src/caffe2-cpu-git/build
```

**Comment by yinghai** [comment]
Thanks for the report. I'm looking into that.

**Comment by yinghai** [comment]
Hi @dbermond, I was not able to reproduce the issue but it seems to have happened in other projects before (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60625#c3). I followed that thread and put up and fix at https://github.com/caffe2/caffe2/pull/2386. Could you cherry-pick and see if it works for you? Thanks.

**Comment by dbermond** [comment]
@yinghai Thank you for the reply and for the attention.

I can confirm that applying #2386 **fixes** this issue.

It generates a non-fatal warning, as follows, but builds fine:
```
[ 64%] Building CXX object caffe2/CMakeFiles/caffe2.dir/operators/index_hash_ops.cc.o
In file included from /storage/linux/abs/caffe2-cpu-git/src/caffe2-cpu-git/caffe2/operators/index_hash_ops.cc:17:0:
/storage/linux/abs/caffe2-cpu-git/src/caffe2-cpu-git/caffe2/operators/index_hash_ops.h:66:60: warning: ‘no_sanitize’ attribute directive ignored [-Wattributes]
   CAFFE2_NO_SANITIZE("signed-integer-overflow") T hash(T id) {
                                                            ^
cc1plus: warning: unrecognized command line option ‘-Wno-invalid-partial-specialization’
```

Thank you for fixing this!

**Comment by yinghai** [comment]
Cool! Note that we don't official support gcc7 yet. So now we can live with this warning. Closing this as https://github.com/caffe2/caffe2/pull/2386 is merged.
