### ISSUE TITLE
Compilation error when using clang as a cuda host compiler

### ISSUE THREAD

**Issue by Jenkyrados** [facebookarchive/caffe2#1483]
Under a stretch system, using clang-3.8 or clang-3.9 :
```
.../caffe2/caffe2/perfkernels/typed_axpy_avx2.cc:35:15: error: use of undeclared identifier '_cvtsh_ss'
    *(y++) += _cvtsh_ss((*(x++)).x) * a;
              ^
.../caffe2/caffe2/perfkernels/typed_axpy_avx.cc:35:15: error: use of undeclared identifier '_cvtsh_ss'
    *(y++) += _cvtsh_ss((*(x++)).x) * a;
              ^
.../caffe2/caffe2/perfkernels/typed_axpy_avx2.cc:56:21: error: use of undeclared identifier '_cvtsh_ss'
      y[current] += _cvtsh_ss(x[current].x) * a;
                    ^
.../caffe2/caffe2/perfkernels/typed_axpy_avx.cc:57:21: error: use of undeclared identifier '_cvtsh_ss'
      y[current] += _cvtsh_ss(x[current].x) * a;
```

This seems similar (identical?) to https://github.com/caffe2/caffe2/issues/1036 , but on a non-apple system.

**Comment by pietern** [comment]
I'm working on adding builds for more compilers (e.g. gcc 6 and clang).

**Comment by pietern** [comment]
Repro: https://ci.pytorch.org/jenkins/job/caffe2-builds/job/caffe2-linux-xenial-clang38-build/1/console

**Comment by pietern** [comment]
This doesn't reproduce on 3.9 through. It builds fine on Ubuntu Xenial clang 3.9.

See: https://ci.pytorch.org/jenkins/job/caffe2-builds/job/caffe2-linux-xenial-clang39-build/1/console

I double checked the clang commit history and see the fix ([D16177](https://reviews.llvm.org/D16177)) is included in 3.9.
