### ISSUE TITLE
Unsupported GNU version!

### ISSUE THREAD

**Issue by bhavesh2g** [facebookarchive/caffe2#442]
/usr/local/cuda-8.0/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!

**Comment by zchrissirhcz** [comment]
Which version of cuda do you use?
For me, I use ubuntu14.04 with GCC5.4.1, follow the official tutorial to install caffe2:https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile

it works for me.

**Comment by bhavesh2g** [comment]
/usr/local/cuda-8.0/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!

I am following the tutorial. CUDA 8+UBUNTU14.04+GCC5

**Comment by xhzzhang** [comment]
You can open host_config.h, you'll found there is have some condition:

#if defined(__GNUC__)
   
#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ > 9)

your GCC version is 5.4.1, is to new for cuda toolkit, i have same problem, then i have follow step to change gcc, then it works well:

$ ls /usr/bin/gcc-*  # to found i have /usr/bin/gcc-4.8
$ sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 40
$ sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.4 40
$ sudo update-alternatives --config gcc
$ sudo update-alternatives --config g++

BTW, @zchrissirhcz, i think you don't have macro '__GNUC__' when compiled, so you can pass.

**Comment by pietern** [comment]
@xhzzhang The code you mention probably comes from an older CUDA version. CUDA 8 only checks if the GCC version is > 5 (i.e. it only supports GCC 5 and below).

@bhavesh2g If you run gcc -v, you'll see your compiler version, which is likely 6 or higher. I have added a check for this in the CMake configuration in #504. You'll have to compile with GCC 4.9, GCC 5, or clang.
